travis:
  secure:
    BINSTAR_TOKEN: mjk1B512Nvt6FEwrsZWFxddcPXvtTcSWLT4ZRIneE2sCit3lVAH5gXcnsg0jfPRlhSyLlDGHc9Yye9BDq9kKHV/SMq80x2wtok0AAfCaDgSmgdVFRcntEkb9yKwyFgPcSAkxWujSaXTzm5I6EsEalEN4VIZXG4coKCtie13/Y07iXvuNdr5gz6ObarliFKm7QzhWGFlPtQt4C9KDaBr4DtrcKfJRY9OZdNvs4gGbv6y76tGk4UyvAurO3k7B9XtghasYskUU6FPz4WhFkldfc3V1jvur8UmUIKTmsLECYGJkahrc0jbfFzrZQP/e911Y4uM9PZo6httXNFH8cleakK/Ij2TiFU6EkfWOY2yZv89EUpRRZ1yaSgXEoARF382PSC4G35bgkmlIEpjfj8qm7U014vqfQcWgpx1Mlc2IW75ZWDn+BDF2E10/ZVLrdS2iHfI6B/sOoNNOsj3T/FXsJmEJE//nKLdHHUVBKgtJTy7/YchRDchNr6RW9FfQb72L3xDV4g4LO45z9n3Un45JrscClHZe+QXGb3aFuFJtGRW5pewOyh0XLFI4cZTgYnVTcKqs+hQSBzT3ipXPrg9jR/pcS677PeF7qkZx1z90UQtw1XvJ6FZBj9GS6yN+cCax/zehjLg0qFDyHlVCHdQM6aK0LBDgYlmm70M7ovH6j+8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
