travis:
  secure:
    BINSTAR_TOKEN: RZGUfWfuMPFvLOfyZblx/CLW3Yx8ozE1KUtASMYl0Cfq4MOp85FpUcYUbdT+NZhMX3N5OV68rKC3IsxAgj7oBJqlwFV72uJ8JHePXwNsXYikPZmDmc25a6oEBfoaSgqqqqXprBXYQ5mtIdgSZP5Rq9kztCVhS5sWefcCy6B3aBjdyyWsMVJfjyTUyrY43uus5NbWj0+iGSBzqt5eeqk9RUQIbe8hO9NpE3GV5rcvkFaVQUb1eSL2CBB+O7w51SX/rtEjNVH5zXpHOFPA2MVEnxHtpksNmRwy70qS8Joke4V+D1aEjFTe/5Tl5lyEmuwdPXJaicC5J9CD23FxWa3M/yxFnEyqHUp46xq5KkNQFq2Gblm42ciKYw+XvO9w/zaa0kYel5g55gm2/mMRjplXEvX+iqLEME/x3Y/g+AGuoY35OrTPMWgQZIzOKZ9UX2t4/UUToCPFP2xfIBc2TJblLC8G3RYPDmToIC+qsliLAWrLKSd3G+GlDS78V9nIfQ/6HAR8vdF9KTQpcDSi2/IViy5emGyNoAqmtZJqC6dmb0hmfGqQ5Yo15FsGS5cwc0aWhPP+mf3q5hvkh/BR/auTsnlWyuoWQWxhy5tLJXaPA6FFB5GgM5KI1zCazJ3aMaUiShKCtaeROF4LJGlOVEFP1Z9otVt30F3tBWMk+PmzQtI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
